### PR TITLE
Fix duplicate spans issue and clean up

### LINKED ISSUE #542: HTTPS plugin results in duplicate spans
### What version of OpenCensus are you using?
I have pulled the the 0.0.13 copy of OpenCensus. 

### What version of Node are you using?
Node v8.12.0 (Mac)

### What did you do?
I have written a simple Express app, and added OpenCensus

```
const express                 = require("express");
const bodyParser              = require('body-parser');
const methodOverride          = require('method-override');
const rp                      = require('request-promise');
const app                     = express();


app.use(bodyParser());
app.use(methodOverride());

app.get('/jsonplaceholder', function(req, res){
  rp('https://jsonplaceholder.typicode.com/todos/1').then(data =>{
    res.status(200).send(data);
  }, err =>{
    res.status(500).json({err: err.message});
  })
})

app.listen(3500, () => console.log("Example app listening on port 3500!"));

module.exports  = app;
```

When I invoke it, and write some code to dump the generated span data I see:
Three spans being generated. 

### What did you expect to see?

Removing the HTTPS plugin results in two spans (one incoming, one outgoing) which is correct.

```JSON
[
  {
    "spanID": "1540e59e60783bc7",
    "name": "/jsonplaceholder",
    "parentSpanId": "",
    "traceID": "2b9646a7b21d43adaa366ee2a45ca943",
    "annotations": {
      "http.user_agent": "insomnia/6.5.1",
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T14:00:49.548Z",
    "endTime": "2019-05-21T14:00:49.626Z",
    "duration": 78.558514
  },
  {
    "spanID": "d2341914c3d4ca96",
    "name": "GET /todos/1",
    "parentSpanId": "1540e59e60783bc7",
    "traceID": "2b9646a7b21d43adaa366ee2a45ca943",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T14:00:49.564Z",
    "endTime": "2019-05-21T14:00:49.621Z",
    "duration": 57.005675
  }
]
```
### What did you see instead?
The outgoing call is registered twice:

```JSON
[
  {
    "spanID": "268bc64f314c0e37",
    "name": "/jsonplaceholder",
    "parentSpanId": "",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "http.user_agent": "insomnia/6.5.1",
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.727Z",
    "endTime": "2019-05-21T13:58:07.877Z",
    "duration": 150.505983
  },
  {
    "spanID": "89d0e0c36415534b",
    "name": "GET /todos/1",
    "parentSpanId": "268bc64f314c0e37",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.745Z",
    "endTime": "2019-05-21T13:58:07.872Z",
    "duration": 127.311449
  },
  {
    "spanID": "12d9fefb36b51eaa",
    "name": "GET /todos/1",
    "parentSpanId": "268bc64f314c0e37",
    "traceID": "828de57c7a444247a59868a6bc8b0745",
    "annotations": {
      "status_code": "200",
      "appName": "default"
    },
    "startTime": "2019-05-21T13:58:07.746Z",
    "endTime": "2019-05-21T13:58:07.872Z",
    "duration": 126.560446
  }
]
```

### PR DESCRIPTION
**Pull request by mayurkale22**
Fixes #542

### CODE REVIEW

**Comment by mayurkale22** [comment]
@hekike Please review.

File: packages/opencensus-core/src/exporters/console-exporter.ts [hunk 1]
```diff
@@ -55,19 +55,24 @@ export class ConsoleExporter implements Exporter {
    * @param span Ended span.
    */
   onEndSpan(span: modelTypes.Span) {
+    // Add spans of a trace together when root is ended, skip non root spans.
+    // publish function will extract child spans from root.
+    if (span.constructor.name !== 'RootSpan') {
```
Comment (hekike) [inline packages/opencensus-core/src/exporters/console-exporter.ts]: should we have an `isRoot` on the span btw?

Comment (mayurkale22) [reply packages/opencensus-core/src/exporters/console-exporter.ts]: Done, 07b564e316be421a5c88e88d85759da735e33c12. PTAL
