### PR TITLE
Make Stackdriver propagation module consistent with other propagations interface

### LINKED ISSUE #340: B3 Propagation UX issues
Working on support for propagation via OpenCensus propagation modules in Stackdriver Trace (https://github.com/googleapis/cloud-trace-nodejs/pull/950), I ran into a couple of issues:

* Because `strictNullChecks` is turned off, `B3Format` does an unsafe non-null cast ([source](https://github.com/census-instrumentation/opencensus-node/blob/38ed0a2dde9c927054c7e392ae7012b89b921577/packages/opencensus-propagation-b3/src/b3-format.ts)). The result is that consumers of this propagation library will get invalid values whenever the B3 header is not set, and crash if they depended on these values being valid (which is a reasonable assumption for TS users).
* Not a behavioral bug but there are a few superfluous falsiness checks in `B3Format` such as for `getter` and `setter`.
* The B3 propagation module exports a different interface than the Stackdriver propagation module. Stackdriver propagation exports an implementation of `Propagation`, while B3 propagation exports a class constructor. I believe they should all export the former rather than the latter.

These issues may also exist for other propagation mechanisms, I only looked at B3 in particular.

### PR DESCRIPTION
**Pull request by mayurkale22**
This PR fixes two things:

1. Stackdriver propagation exports an implementation of Propagation, while `B3`, `Binary Format`, `TraceContext` and `Jaeger` propagation exports a class constructor. Fixes #340
2. Enforce `strictNullChecks` and `noUnusedLocals` on Stackdriver propagation package. This is part of #348

### CODE REVIEW

File: packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+import {StackdriverFormat, TRACE_CONTEXT_HEADER_NAME} from '../src';
+
+const stackdriverFormat = new StackdriverFormat();
+
+describe('StackdriverPropagation', () => {
+  describe('extract()', () => {
+    it('should extract context of a sampled span from headers', () => {
+      const headers: {[key: string]: string|string[]|undefined} = {};
+      headers[TRACE_CONTEXT_HEADER_NAME] = '123456/667;o=1';
+      const getter: HeaderGetter = {
```
Comment (draffensperger) [inline packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts]: Would it make sense to abstract this into a helper function to share it between these different test cases?

File: packages/opencensus-propagation-stackdriver/src/stackdriver-format.ts [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+      header += `;o=${spanContext.options}`;
+    }
+
+    setter.setHeader(TRACE_CONTEXT_HEADER_NAME, header);
+  }
+
+  /** Generate SpanContexts */
+  generate(): SpanContext {
+    return {
+      traceId: uuid.v4().split('-').join(''),
```
Comment (draffensperger) [inline packages/opencensus-propagation-stackdriver/src/stackdriver-format.ts]: Optional: would it make sense to do `uuid.v4().replace('-', '')`

Comment (mayurkale22) [reply packages/opencensus-propagation-stackdriver/src/stackdriver-format.ts]: SG, done. As per https://jsfiddle.net/basickarl/re5ywuum/ test, fastest is replace.

File: packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts (hunk 1 above)
Comment (mayurkale22) [reply packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts]: Sure, done

**Comment by mayurkale22** [comment]
@kjin As this fixes your issue #340, It will be nice to have reviews from you.

**Comment by mayurkale22** [comment]
> LGTM, in the future it would be great if the CI shows green before requesting reviews.

Sure, btw current build failure wasn't related to this change.
