### PR TITLE
Exporter/Stats/Stackdriver: Fix MetricDescriptors ValueType

### LINKED ISSUE #178: StackdriverStatsExporter: valueType to string
Change valueType to use string instead of number

### PR DESCRIPTION
**Pull request by mayurkale22**
Fixes #178

### CODE REVIEW

File: packages/opencensus-exporter-stackdriver/src/types.ts [hunk 1]
```diff
@@ -72,13 +72,13 @@ export enum MetricKind {
...
-  STRING,
-  DISTRIBUTION,
-  MONEY
+  VALUE_TYPE_UNSPECIFIED = 'VALUE_TYPE_UNSPECIFIED',
+  BOOL = 'BOOL',
+  INT64 = 'INT64',
+  DOUBLE = 'DOUBLE',
+  STRING = 'STRING',
+  DISTRIBUTION = 'DISTRIBUTION',
+  MONEY = 'MONEY'
```
Comment (bogdandrutu) [inline packages/opencensus-exporter-stackdriver/src/types.ts]: I don't think we support "Money", "String" and "Bool". Do we still need them here?

Comment (mayurkale22) [reply packages/opencensus-exporter-stackdriver/src/types.ts]: I don't think we need that, looks like previously copied from https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#ValueType list.

Comment (mayurkale22) [reply packages/opencensus-exporter-stackdriver/src/types.ts]: Removed.
